name: Backup Selected Repositories

on:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Sync Selected Repositories
        env:
          BACKUP_TOKEN: ${{ secrets.BACKUP_TOKEN }}
        run: |
          PRIMARY_USER="pspaymentgateway"
          BACKUP_USER="PaysecureMicroServices"

          REPOS=("PaySecureSDK_Python")   # start with 1 repo for testing

          for repo in "${REPOS[@]}"; do
            echo "Processing $repo"

             # Mirror clone (includes ALL branches, tags, refs)
            git clone --mirror https://github.com/$PRIMARY_USER/$repo.git
            cd $repo.git
  
            # Add backup remote
            git remote add backup https://$BACKUP_TOKEN@github.com/$BACKUP_USER/$repo.git
  
            # Mirror push (exact sync)
            git push backup --mirror
            echo "Sync completed"
          done
